[package]
name = "phplsp"
version = "0.1.0"
edition = "2021"
description = "A very bad implementation of a PHP Language Server, in Rust of course."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.125"
tokio = { version = "1.39.2", features = ["full"] }
tower-lsp = "0.20.0"
tree-sitter = "0.22.6"
tree-sitter-php = "0.22.8"

[build-dependencies]
cc = "*"
