name: Deploy mdBook site to Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          key: mdbook-v0.4.49
          path: ./bin
      - name: Install mdBook
        run: |
          mkdir bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.49/mdbook-v0.4.49-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
      - name: Build the book
        run: bin/mdbook build docs/book/
      - name: Upload the artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book/book

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to pages
        id: deployment
        uses: actions/deploy-pages@v4
