name: Rust

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.rs'
      - Cargo.toml
      - 'tree-sitter-phpdoc/**'
      - 'phpstorm-stubs/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - '**.rs'
      - Cargo.toml
      - 'tree-sitter-phpdoc/**'
      - 'phpstorm-stubs/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: actions/cache@v4
      with:
        path: |
          target
          ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
